import type { Product } from './cart-context'

export const products: Product[] = [
  {
    id: '1',
    name: 'Rose Petal Radiance Serum',
    price: 2499,
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=500&fit=crop',
    category: 'Skincare',
    description: 'A luxurious serum infused with rose petal extract for radiant, glowing skin. Perfect for all skin types.',
    rating: 4.8,
    reviews: 124,
    inStock: true,
  },
  {
    id: '2',
    name: 'Golden Glow Foundation',
    price: 1899,
    image: 'https://images.unsplash.com/photo-1631730486572-226d1f595b68?w=400&h=500&fit=crop',
    category: 'Makeup',
    description: 'Lightweight, buildable coverage foundation with golden undertones for a natural, luminous finish.',
    rating: 4.6,
    reviews: 89,
    inStock: true,
  },
  {
    id: '3',
    name: 'Velvet Matte Lipstick',
    price: 899,
    image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=400&h=500&fit=crop',
    category: 'Lips',
    description: 'Long-lasting velvet matte formula in stunning shades that feel comfortable all day.',
    rating: 4.9,
    reviews: 256,
    inStock: true,
  },
  {
    id: '4',
    name: 'Hydrating Night Cream',
    price: 1699,
    image: 'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=400&h=500&fit=crop',
    category: 'Skincare',
    description: 'Intensive overnight treatment with hyaluronic acid and vitamin E for deep hydration.',
    rating: 4.7,
    reviews: 178,
    inStock: true,
  },
  {
    id: '5',
    name: 'Charizma Eye Palette',
    price: 2199,
    image: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=400&h=500&fit=crop',
    category: 'Eyes',
    description: '12 stunning shades from everyday neutrals to bold metallics for endless eye looks.',
    rating: 4.8,
    reviews: 312,
    inStock: true,
  },
  {
    id: '6',
    name: 'Vitamin C Brightening Mask',
    price: 1299,
    image: 'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=400&h=500&fit=crop',
    category: 'Skincare',
    description: 'Powerful vitamin C treatment mask that brightens and evens skin tone in just 15 minutes.',
    rating: 4.5,
    reviews: 145,
    inStock: true,
  },
  {
    id: '7',
    name: 'Silk Setting Powder',
    price: 1499,
    image: 'https://images.unsplash.com/photo-1599733589146-8d6b87f8c8d2?w=400&h=500&fit=crop',
    category: 'Makeup',
    description: 'Finely milled setting powder that sets makeup for hours without looking cakey.',
    rating: 4.6,
    reviews: 198,
    inStock: true,
  },
  {
    id: '8',
    name: 'Luxury Hair Oil',
    price: 1899,
    image: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=400&h=500&fit=crop',
    category: 'Hair',
    description: 'Nourishing hair oil blend with argan and jojoba for silky, frizz-free locks.',
    rating: 4.9,
    reviews: 267,
    inStock: true,
  },
  {
    id: '9',
    name: 'Retinol Anti-Aging Cream',
    price: 2799,
    image: 'https://images.unsplash.com/photo-1570194065650-d99fb4d8a609?w=400&h=500&fit=crop',
    category: 'Skincare',
    description: 'Advanced retinol formula that reduces fine lines and wrinkles for youthful skin.',
    rating: 4.7,
    reviews: 189,
    inStock: true,
  },
  {
    id: '10',
    name: 'Blush Duo Palette',
    price: 1199,
    image: 'https://images.unsplash.com/photo-1503236823255-94609f598e71?w=400&h=500&fit=crop',
    category: 'Makeup',
    description: 'Two complementary blush shades for a natural flush or bold statement look.',
    rating: 4.5,
    reviews: 134,
    inStock: true,
  },
  {
    id: '11',
    name: 'Charcoal Detox Cleanser',
    price: 999,
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=500&fit=crop',
    category: 'Skincare',
    description: 'Deep cleansing formula with activated charcoal to remove impurities and excess oil.',
    rating: 4.4,
    reviews: 156,
    inStock: true,
  },
  {
    id: '12',
    name: 'Lash Volume Mascara',
    price: 799,
    image: 'https://images.unsplash.com/photo-1631214524020-7e18db9a8f92?w=400&h=500&fit=crop',
    category: 'Eyes',
    description: 'Dramatic volume mascara with conditioning formula for fuller, longer-looking lashes.',
    rating: 4.8,
    reviews: 423,
    inStock: true,
  },
]

export const categories = ['All', 'Skincare', 'Makeup', 'Lips', 'Eyes', 'Hair']

export const collections = [
  {
    id: 'skincare',
    name: 'Skincare Essentials',
    description: 'Nourish your skin with our premium collection',
    image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600&h=400&fit=crop',
  },
  {
    id: 'makeup',
    name: 'Makeup Collection',
    description: 'Express yourself with our stunning makeup range',
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&h=400&fit=crop',
  },
  {
    id: 'bridal',
    name: 'Bridal Beauty',
    description: 'Look flawless on your special day',
    image: 'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=600&h=400&fit=crop',
  },
]

export const testimonials = [
  {
    id: '1',
    name: 'Priya Sharma',
    location: 'Shivpuri',
    rating: 5,
    text: 'Charizma has been my go-to for skincare for years. The quality is unmatched and the staff is incredibly knowledgeable.',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop',
  },
  {
    id: '2',
    name: 'Anjali Verma',
    location: 'Gwalior',
    rating: 5,
    text: 'My bridal makeup was absolutely stunning. They understood exactly what I wanted and made me feel like a queen.',
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop',
  },
  {
    id: '3',
    name: 'Meera Patel',
    location: 'Bhopal',
    rating: 5,
    text: 'The Rose Petal Serum has transformed my skin. I get compliments every day now. Thank you, Charizma!',
    image: 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=100&h=100&fit=crop',
  },
  {
    id: '4',
    name: 'Kavita Singh',
    location: 'Shivpuri',
    rating: 5,
    text: 'Professional service and premium products. Charizma has been serving our family for generations.',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop',
  },
]

export const services = [
  {
    id: '1',
    name: 'Bridal Makeup',
    duration: '3-4 hours',
    price: 15000,
    description: 'Complete bridal makeover including hair styling and makeup',
  },
  {
    id: '2',
    name: 'Facial Treatment',
    duration: '1 hour',
    price: 1500,
    description: 'Deep cleansing facial with premium products',
  },
  {
    id: '3',
    name: 'Hair Styling',
    duration: '1-2 hours',
    price: 2500,
    description: 'Professional hair styling for any occasion',
  },
  {
    id: '4',
    name: 'Skincare Consultation',
    duration: '30 mins',
    price: 500,
    description: 'Personalized skincare routine recommendation',
  },
  {
    id: '5',
    name: 'Makeup Lesson',
    duration: '2 hours',
    price: 3000,
    description: 'Learn professional makeup techniques',
  },
  {
    id: '6',
    name: 'Full Body Treatment',
    duration: '4-5 hours',
    price: 8000,
    description: 'Complete body spa and treatment package',
  },
]
